version: '2'
services:
  db:
      image: mysql:8.0.28
      container_name: cs351AcmeTravelDatabase
      # Uncomment the line below if you're on a new Apple M1 computer
      platform: linux/amd64
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: changeme
        MYSQL_DATABASE: app
        MYSQL_USER: user
        MYSQL_PASSWORD: password
#      ports:
#        - "3307:3306"
      volumes:
        - ./mysql_data:/var/lib/mysql
  app:
    build: .
    container_name: cs351AcmeTravelRails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/app"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: app
      DB_PASSWORD: changeme
      DB_HOST: db

volumes:
  mysql_data:
